id: P18524656
initial_creation_type: input
source_metadata:
  Title: Pramāṇavārtikam
  Editor: Pandey, R.C.
  Publisher: Motilal Banarsidas
  Place of Publication: Delhi, India
  Year: '1989'
  Prathamaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dvitīyaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Tṛtīyaḥ svārthānumānaparicchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Parārthānumānanāmā caturthaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:49:35.246250'
last_modified_at: '2022-03-08T16:49:35.246262'
